const Exception = {
    // Product
    CANNOT_ADD_PRODUCT: 'CANNOT_ADD_PRODUCT',
    CANNOT_ADD_PRODUCT_INVENTORY: 'CANNOT_ADD_PRODUCT_INVENTORY',
    // Inventory
    CANNOT_CREATE_INVENTORY_HISTORY: 'CANNOT_CREATE_INVENTORY_HISTORY',
};

export default Exception;